database.name=drs
database.serverUrl=jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Australia/Sydney
database.url=jdbc:mysql://localhost:3306/drs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Australia/Sydney
database.username=root
database.password=Test$123
